<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" ignored="0" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Portal Automation Testing" duration-ms="12036" started-at="2019-05-09T09:26:23Z" finished-at="2019-05-09T09:26:35Z">
    <groups>
    </groups>
    <test name="R03" duration-ms="12036" started-at="2019-05-09T09:26:23Z" finished-at="2019-05-09T09:26:35Z">
      <class name="com.qa.tests.R03">
        <test-method status="PASS" signature="start()[pri:0, instance:com.qa.tests.R03@2d710f1a]" name="start" is-config="true" duration-ms="3817" started-at="2019-05-09T14:56:19Z" finished-at="2019-05-09T14:56:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="startUp()[pri:0, instance:com.qa.tests.R03@2d710f1a]" name="startUp" is-config="true" duration-ms="29" started-at="2019-05-09T14:56:23Z" finished-at="2019-05-09T14:56:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startUp -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.tests.R03@2d710f1a]" name="setUp" is-config="true" duration-ms="40" started-at="2019-05-09T14:56:23Z" finished-at="2019-05-09T14:56:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.tests.R03.TC_374980(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="TC_374980(java.util.Hashtable)[pri:1, instance:com.qa.tests.R03@2d710f1a]" name="TC_374980" duration-ms="9414" started-at="2019-05-09T14:56:23Z" data-provider="dataProvider" finished-at="2019-05-09T14:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{url=https://qa2012r2-vr3.inqa.soti.net/login, app_type=MobiControl, instance_name=, validation_message2=, Test_Case=TC_374980, validation_message=, account_type=Soti DB, username=vdtenant@yopmail.com, runmode=Y, password=Welcome12345}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_374980 -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.tests.R03@2d710f1a]" name="setUp" is-config="true" duration-ms="38" started-at="2019-05-09T14:56:33Z" finished-at="2019-05-09T14:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.tests.R03.TC_375423_375424(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="TC_375423_375424(java.util.Hashtable)[pri:2, instance:com.qa.tests.R03@2d710f1a]" name="TC_375423_375424" duration-ms="21" started-at="2019-05-09T14:56:33Z" data-provider="dataProvider" finished-at="2019-05-09T14:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{url=https://qa2012r2-vr3.inqa.soti.net/login, app_type=MobiControl, instance_name=123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_1, validation_message2=MobiControl Instance Name cannot exceed 100 characters, Test_Case=TC_375423_375424, validation_message=MobiControl Instance Name is required, account_type=Soti DB, username=vdtenant@yopmail.com, runmode=N, password=Welcome12345}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode of the test data is set to NO for class: R03 --- Test Case: TC_375423_375424]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode of the test data is set to NO for class: R03 --- Test Case: TC_375423_375424
	at com.qa.util.readAndWriteData.runmodeCheck(readAndWriteData.java:84)
	at com.qa.base.TestBase.initial_test_tasks(TestBase.java:187)
	at com.qa.tests.R03.TC_375423_375424(R03.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.qa.tests.runner.test_runner(runner.java:76)
	at com.qa.tests.runner.main(runner.java:83)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_375423_375424 -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.tests.R03@2d710f1a]" name="setUp" is-config="true" duration-ms="40" started-at="2019-05-09T14:56:33Z" finished-at="2019-05-09T14:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.tests.R03.TC_375426(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="TC_375426(java.util.Hashtable)[pri:3, instance:com.qa.tests.R03@2d710f1a]" name="TC_375426" duration-ms="16" started-at="2019-05-09T14:56:33Z" data-provider="dataProvider" finished-at="2019-05-09T14:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{url=https://qa2012r2-vr3.inqa.soti.net/login, app_type=MobiControl, instance_name=123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_1, validation_message2=MobiControl Instance Name cannot exceed 100 characters, Test_Case=TC_375426, validation_message=MobiControl Instance Name is required, account_type=Soti DB, username=vdtenant@yopmail.com, runmode=N, password=Welcome12345}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode of the test data is set to NO for class: R03 --- Test Case: TC_375426]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode of the test data is set to NO for class: R03 --- Test Case: TC_375426
	at com.qa.util.readAndWriteData.runmodeCheck(readAndWriteData.java:84)
	at com.qa.base.TestBase.initial_test_tasks(TestBase.java:187)
	at com.qa.tests.R03.TC_375426(R03.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.qa.tests.runner.test_runner(runner.java:76)
	at com.qa.tests.runner.main(runner.java:83)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_375426 -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.tests.R03@2d710f1a]" name="setUp" is-config="true" duration-ms="40" started-at="2019-05-09T14:56:33Z" finished-at="2019-05-09T14:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.tests.R03.deleteApplication(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="deleteApplication(java.util.Hashtable)[pri:4, instance:com.qa.tests.R03@2d710f1a]" name="deleteApplication" duration-ms="16" started-at="2019-05-09T14:56:33Z" data-provider="dataProvider" finished-at="2019-05-09T14:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{url=https://qa2012r2-vr3.inqa.soti.net/login, app_type=MobiControl, instance_name=123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_1, validation_message2=MobiControl Instance Name cannot exceed 100 characters, Test_Case=deleteApplication, validation_message=MobiControl Instance Name is required, account_type=Soti DB, username=vdtenant@yopmail.com, runmode=N, password=Welcome12345}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode of the test data is set to NO for class: R03 --- Test Case: deleteApplication]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode of the test data is set to NO for class: R03 --- Test Case: deleteApplication
	at com.qa.util.readAndWriteData.runmodeCheck(readAndWriteData.java:84)
	at com.qa.base.TestBase.initial_test_tasks(TestBase.java:187)
	at com.qa.tests.R03.deleteApplication(R03.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.qa.tests.runner.test_runner(runner.java:76)
	at com.qa.tests.runner.main(runner.java:83)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteApplication -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.tests.R03@2d710f1a]" name="setUp" is-config="true" duration-ms="44" started-at="2019-05-09T14:56:33Z" finished-at="2019-05-09T14:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.tests.R03.account(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="account(java.util.Hashtable)[pri:5, instance:com.qa.tests.R03@2d710f1a]" name="account" duration-ms="2186" started-at="2019-05-09T14:56:33Z" data-provider="dataProvider" finished-at="2019-05-09T14:56:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{url=https://qa2012r2-vr3.inqa.soti.net/login, app_type=MobiControl, instance_name=123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_1, validation_message2=MobiControl Instance Name cannot exceed 100 characters, Test_Case=account, validation_message=MobiControl Instance Name is required, account_type=Soti DB, username=vdtenant@yopmail.com, runmode=Y, password=Welcome12345}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- account -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.tests.R03@2d710f1a]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-05-09T14:56:35Z" finished-at="2019-05-09T14:56:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="shudown()[pri:0, instance:com.qa.tests.R03@2d710f1a]" name="shudown" is-config="true" duration-ms="679" started-at="2019-05-09T14:56:35Z" finished-at="2019-05-09T14:56:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shudown -->
      </class> <!-- com.qa.tests.R03 -->
    </test> <!-- R03 -->
  </suite> <!-- Portal Automation Testing -->
</testng-results>
