<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="1" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-11-13T16:04:54Z" name="Portal Automation Testing" finished-at="2018-11-13T16:05:23Z" duration-ms="28845">
    <groups>
    </groups>
    <test started-at="2018-11-13T16:04:54Z" name="LoginPageTest" finished-at="2018-11-13T16:05:16Z" duration-ms="21796">
      <class name="com.qa.tests.LoginPageTest">
        <test-method is-config="true" signature="startUp()[pri:0, instance:com.qa.tests.LoginPageTest@62f4ff3b]" started-at="2018-11-13T16:04:54Z" name="startUp" finished-at="2018-11-13T16:04:56Z" duration-ms="2202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startUp -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.tests.LoginPageTest@62f4ff3b]" started-at="2018-11-13T16:04:56Z" name="setUp" finished-at="2018-11-13T16:04:56Z" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.tests.LoginPageTest.loginPageTitleTest(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginPageTitleTest(java.util.Hashtable)[pri:0, instance:com.qa.tests.LoginPageTest@62f4ff3b]" started-at="2018-11-13T16:04:56Z" name="loginPageTitleTest" data-provider="dataProvider" finished-at="2018-11-13T16:05:10Z" duration-ms="13718" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Test_Case=loginPageTitleTest, runmode=Y}]]>
              </value>
            </param>
          </params>
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.fail(Assert.java:56)
at com.qa.tests.LoginPageTest.loginPageTitleTest(LoginPageTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.qa.tests.runner.test_runner(runner.java:50)
at com.qa.tests.runner.main(runner.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.tests.LoginPageTest@62f4ff3b]" started-at="2018-11-13T16:05:16Z" name="tearDown" finished-at="2018-11-13T16:05:16Z" duration-ms="97" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.tests.LoginPageTest -->
    </test> <!-- LoginPageTest -->
    <test started-at="2018-11-13T16:05:21Z" name="MyFirstTest" finished-at="2018-11-13T16:05:23Z" duration-ms="1664">
      <class name="com.qa.tests.MyFirstTest">
        <test-method is-config="true" signature="startUp()[pri:0, instance:com.qa.tests.MyFirstTest@758c83d8]" started-at="2018-11-13T16:05:21Z" name="startUp" finished-at="2018-11-13T16:05:22Z" duration-ms="1388" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startUp -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.tests.MyFirstTest@758c83d8]" started-at="2018-11-13T16:05:23Z" name="setUp" finished-at="2018-11-13T16:05:23Z" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.tests.MyFirstTest.myFirstTestt(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="myFirstTestt(java.util.Hashtable)[pri:0, instance:com.qa.tests.MyFirstTest@758c83d8]" started-at="2018-11-13T16:05:23Z" name="myFirstTestt" data-provider="dataProvider" finished-at="2018-11-13T16:05:23Z" duration-ms="37" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{url=https://www.ashurst.com/, Test_Case=myFirstTestt, testdata=Vivek, runmode=Y}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode of the test data is set to NO for class: MyFirstTest]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode of the test data is set to NO for class: MyFirstTest
at com.qa.util.readAndWriteData.runmodeCheck(readAndWriteData.java:46)
at com.qa.base.TestBase.initial_test_tasks(TestBase.java:170)
at com.qa.tests.MyFirstTest.myFirstTestt(MyFirstTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.qa.tests.runner.test_runner(runner.java:50)
at com.qa.tests.runner.main(runner.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFirstTestt -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.tests.MyFirstTest@758c83d8]" started-at="2018-11-13T16:05:23Z" name="setUp" finished-at="2018-11-13T16:05:23Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.tests.MyFirstTest.myFirstTestt(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="myFirstTestt(java.util.Hashtable)[pri:0, instance:com.qa.tests.MyFirstTest@758c83d8]" started-at="2018-11-13T16:05:23Z" name="myFirstTestt" data-provider="dataProvider" finished-at="2018-11-13T16:05:23Z" duration-ms="34" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{url=https://www.ashurst.com/, Test_Case=myFirstTestt, testdata=Dubey, runmode=Y}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode of the test data is set to NO for class: MyFirstTest]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode of the test data is set to NO for class: MyFirstTest
at com.qa.util.readAndWriteData.runmodeCheck(readAndWriteData.java:46)
at com.qa.base.TestBase.initial_test_tasks(TestBase.java:170)
at com.qa.tests.MyFirstTest.myFirstTestt(MyFirstTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.qa.tests.runner.test_runner(runner.java:50)
at com.qa.tests.runner.main(runner.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFirstTestt -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.qa.tests.MyFirstTest@758c83d8]" started-at="2018-11-13T16:05:23Z" name="setUp" finished-at="2018-11-13T16:05:23Z" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.tests.MyFirstTest.mySecondTestt(java.util.Hashtable)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="mySecondTestt(java.util.Hashtable)[pri:0, instance:com.qa.tests.MyFirstTest@758c83d8]" started-at="2018-11-13T16:05:23Z" name="mySecondTestt" data-provider="dataProvider" finished-at="2018-11-13T16:05:23Z" duration-ms="34" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{url=https://www.ashurst.com/, Test_Case=mySecondTestt, testdata=Avinash, runmode=Y}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode of the test data is set to NO for class: MyFirstTest]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode of the test data is set to NO for class: MyFirstTest
at com.qa.util.readAndWriteData.runmodeCheck(readAndWriteData.java:46)
at com.qa.base.TestBase.initial_test_tasks(TestBase.java:170)
at com.qa.tests.MyFirstTest.mySecondTestt(MyFirstTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.qa.tests.runner.test_runner(runner.java:50)
at com.qa.tests.runner.main(runner.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySecondTestt -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.tests.MyFirstTest@758c83d8]" started-at="2018-11-13T16:05:23Z" name="tearDown" finished-at="2018-11-13T16:05:23Z" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.tests.MyFirstTest -->
    </test> <!-- MyFirstTest -->
  </suite> <!-- Portal Automation Testing -->
</testng-results>
