<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Viveks-MacBook-Air.local" failures="1" tests="3" name="MyFirstTest" time="26.089" errors="0" timestamp="18 Nov 2018 14:08:35 GMT">
  <testcase classname="com.qa.tests.MyFirstTest" name="myFirstTestt" time="17.095">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.fail(Assert.java:56)
at com.qa.tests.MyFirstTest.myFirstTestt(MyFirstTest.java:22)
at com.qa.tests.runner.test_runner(runner.java:74)
at com.qa.tests.runner.main(runner.java:81)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- myFirstTestt -->
  <testcase classname="com.qa.tests.MyFirstTest" name="myFirstTestt" time="0.002">
    <skipped/>
  </testcase> <!-- myFirstTestt -->
  <testcase classname="com.qa.tests.MyFirstTest" name="mySecondTestt" time="7.045"/>
</testsuite> <!-- MyFirstTest -->
